server:
  port: 8090

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  constants:
    secret-key: 'challengebcp'
    token-response-format: 'Bearer %s'


